import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import dataFetch from "../utils/";
import { Line } from "react-chartjs-2";

export default function Home() {
  const [data, setData] = useState(null);
  const [SOA, setSumOfAll] = useState(null);
  useEffect(() => {
    const d = dataFetch();
    const labels = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];
    const sumArray = [];
    for (const each of labels) {
      const sum = 0;
      d.forEach((x) => {
        if (new Date(x.endTime).getMonth() == each) sum += x.msPlayed;
      });
      sumArray.push(sum);
    }
    const dataArr = sumArray.map((each) => (each /= 3600000));
    const sumOfAll = dataArr.reduce((cur, ac) => cur + ac);
    const labelArray = dataArr.map((x) => parseInt(x));
    setSumOfAll(sumOfAll);
    const data = {
      labels: labels,
      datasets: [
        {
          label: `Hours each Month`,
          data: dataArr,
          fill: true,
          borderColor: "rgb(75, 192, 192)",
          tension: 0.3,
        },
      ],
    };
    setData(data);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify Listening Analyzer</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.chartD}>
          <h1>Total hours Listened to: {data && parseInt(SOA)}</h1>
          {data && <Line data={data} />}
        </div>
      </main>
    </div>
  );
}
